"""Constants for KEMS."""

from __future__ import annotations

DOMAIN = "kems"
NAME = "KEMS"
VERSION = "0.3.0-alpha1"

DEFAULT_SCAN_INTERVAL_SECONDS = 60
DEFAULT_HISTORY_DAYS = 90
DEFAULT_RECORD_INTERVAL_SECONDS = 300

CONF_CURRENT_IMPORT_RATE = "current_import_rate"
CONF_NEXT_IMPORT_RATE = "next_import_rate"
CONF_CURRENT_EXPORT_RATE = "current_export_rate"
CONF_OFF_PEAK = "off_peak"
CONF_INTELLIGENT_SLOT = "intelligent_slot"
CONF_NEXT_OFFPEAK_START = "next_offpeak_start"
CONF_OFFPEAK_END = "offpeak_end"

CONF_EV_STATUS = "ev_status"
CONF_EV_CONNECTED = "ev_connected"
CONF_EV_CHARGING = "ev_charging"
CONF_EV_POWER = "ev_power_kw"
CONF_EV_SOC = "ev_soc"

CONF_HOUSE_LOAD = "house_load_kw"
CONF_BATTERY_SOC = "battery_soc"
CONF_BATTERY_POWER = "battery_power_kw"
CONF_BATTERY_VOLTAGE = "battery_voltage"
CONF_BATTERY_CURRENT = "battery_current"
CONF_SOLAR_POWER = "solar_power_kw"
CONF_GRID_IMPORT = "grid_import_kw"
CONF_GRID_EXPORT = "grid_export_kw"

ENTITY_MAPPING_KEYS = (
    CONF_CURRENT_IMPORT_RATE,
    CONF_NEXT_IMPORT_RATE,
    CONF_CURRENT_EXPORT_RATE,
    CONF_OFF_PEAK,
    CONF_INTELLIGENT_SLOT,
    CONF_NEXT_OFFPEAK_START,
    CONF_OFFPEAK_END,
    CONF_EV_STATUS,
    CONF_EV_CONNECTED,
    CONF_EV_CHARGING,
    CONF_EV_POWER,
    CONF_EV_SOC,
    CONF_HOUSE_LOAD,
    CONF_BATTERY_SOC,
    CONF_BATTERY_POWER,
    CONF_BATTERY_VOLTAGE,
    CONF_BATTERY_CURRENT,
    CONF_SOLAR_POWER,
    CONF_GRID_IMPORT,
    CONF_GRID_EXPORT,
)

REQUIRED_ENTITY_KEYS = (CONF_CURRENT_IMPORT_RATE,)

CONF_SCAN_INTERVAL = "scan_interval_seconds"
CONF_HISTORY_DAYS = "history_days"
CONF_BATTERY_CAPACITY = "battery_capacity_kwh"
CONF_BATTERY_RESERVE = "battery_reserve_percent"
CONF_BATTERY_INITIAL = "battery_initial_percent"
CONF_MAX_CHARGE = "max_charge_kw"
CONF_MAX_DISCHARGE = "max_discharge_kw"
CONF_CHARGE_EFFICIENCY = "charge_efficiency"
CONF_DISCHARGE_EFFICIENCY = "discharge_efficiency"
CONF_EXPORT_RATE = "export_rate_pence"
CONF_SIMULATION_STRATEGY = "simulation_strategy"

DEFAULT_OPTIONS = {
    CONF_SCAN_INTERVAL: DEFAULT_SCAN_INTERVAL_SECONDS,
    CONF_HISTORY_DAYS: DEFAULT_HISTORY_DAYS,
    CONF_BATTERY_CAPACITY: 56.42,
    CONF_BATTERY_RESERVE: 10.0,
    CONF_BATTERY_INITIAL: 10.0,
    CONF_MAX_CHARGE: 10.0,
    CONF_MAX_DISCHARGE: 10.0,
    CONF_CHARGE_EFFICIENCY: 0.95,
    CONF_DISCHARGE_EFFICIENCY: 0.95,
    CONF_EXPORT_RATE: 0.0,
    CONF_SIMULATION_STRATEGY: "export_first",
}
