"""Constants for KEMS."""

from __future__ import annotations

DOMAIN = "kems"
NAME = "KEMS"
VERSION = "0.7.0-alpha7"

DEFAULT_SCAN_INTERVAL_SECONDS = 60
DEFAULT_HISTORY_DAYS = 90
DEFAULT_RECORD_INTERVAL_SECONDS = 300
STORAGE_NAMESPACE = "clean_v6_alpha2"
SIMULATION_LEDGER_VERSION = 5

CONF_CURRENT_IMPORT_RATE = "current_import_rate"
CONF_NEXT_IMPORT_RATE = "next_import_rate"
CONF_CURRENT_EXPORT_RATE = "current_export_rate"
CONF_ELECTRICITY_STANDING_CHARGE = "electricity_standing_charge"
CONF_OFF_PEAK = "off_peak"
CONF_INTELLIGENT_SLOT = "intelligent_slot"
CONF_NEXT_OFFPEAK_START = "next_offpeak_start"
CONF_OFFPEAK_END = "offpeak_end"
CONF_SAVING_SESSION_EVENTS = "saving_session_events"
CONF_SAVING_SESSION_IMPORT_BASELINE = "saving_session_import_baseline"
CONF_SAVING_SESSION_EXPORT_BASELINE = "saving_session_export_baseline"

CONF_GAS_CURRENT_RATE = "gas_current_rate"
CONF_GAS_STANDING_CHARGE = "gas_standing_charge"
CONF_GAS_METER_TOTAL = "gas_meter_total"
CONF_GAS_USAGE_TODAY = "gas_usage_today"
CONF_GAS_COST_TODAY = "gas_cost_today"

CONF_EV_STATUS = "ev_status"
CONF_EV_CONNECTED = "ev_connected"
CONF_EV_CHARGING = "ev_charging"
CONF_EV_POWER = "ev_power_kw"
CONF_EV_SOC = "ev_soc"

CONF_HOUSE_LOAD = "house_load_kw"
CONF_BATTERY_SOC = "battery_soc"
CONF_BATTERY_POWER = "battery_power_kw"
CONF_BATTERY_VOLTAGE = "battery_voltage"
CONF_BATTERY_CURRENT = "battery_current"
CONF_SOLAR_POWER = "solar_power_kw"
CONF_GRID_IMPORT = "grid_import_kw"
CONF_GRID_EXPORT = "grid_export_kw"

ENTITY_MAPPING_KEYS = (
    CONF_CURRENT_IMPORT_RATE,
    CONF_NEXT_IMPORT_RATE,
    CONF_CURRENT_EXPORT_RATE,
    CONF_ELECTRICITY_STANDING_CHARGE,
    CONF_OFF_PEAK,
    CONF_INTELLIGENT_SLOT,
    CONF_NEXT_OFFPEAK_START,
    CONF_OFFPEAK_END,
    CONF_SAVING_SESSION_EVENTS,
    CONF_SAVING_SESSION_IMPORT_BASELINE,
    CONF_SAVING_SESSION_EXPORT_BASELINE,
    CONF_GAS_CURRENT_RATE,
    CONF_GAS_STANDING_CHARGE,
    CONF_GAS_METER_TOTAL,
    CONF_GAS_USAGE_TODAY,
    CONF_GAS_COST_TODAY,
    CONF_EV_STATUS,
    CONF_EV_CONNECTED,
    CONF_EV_CHARGING,
    CONF_EV_POWER,
    CONF_EV_SOC,
    CONF_HOUSE_LOAD,
    CONF_BATTERY_SOC,
    CONF_BATTERY_POWER,
    CONF_BATTERY_VOLTAGE,
    CONF_BATTERY_CURRENT,
    CONF_SOLAR_POWER,
    CONF_GRID_IMPORT,
    CONF_GRID_EXPORT,
)

REQUIRED_ENTITY_KEYS = (CONF_CURRENT_IMPORT_RATE,)


CONF_TARIFF_MODE = "tariff_mode"
CONF_MANUAL_DAY_RATE = "manual_day_rate_pence"
CONF_MANUAL_OFFPEAK_RATE = "manual_offpeak_rate_pence"
CONF_MANUAL_STANDING_CHARGE = "manual_standing_charge_pence"
CONF_MANUAL_OFFPEAK_START = "manual_offpeak_start"
CONF_MANUAL_OFFPEAK_END = "manual_offpeak_end"
CONF_INTELLIGENT_SLOTS_ENABLED = "intelligent_slots_enabled"

CONF_SCAN_INTERVAL = "scan_interval_seconds"
CONF_HISTORY_DAYS = "history_days"
CONF_BATTERY_CAPACITY = "battery_capacity_kwh"
CONF_BATTERY_RESERVE = "battery_reserve_percent"
CONF_BATTERY_INITIAL = "battery_initial_percent"
CONF_MAX_CHARGE = "max_charge_kw"
CONF_MAX_DISCHARGE = "max_discharge_kw"
CONF_CHARGE_EFFICIENCY = "charge_efficiency"
CONF_DISCHARGE_EFFICIENCY = "discharge_efficiency"
CONF_EXPORT_RATE = "export_rate_pence"
CONF_EXPORT_TARIFF_STATUS = "export_tariff_status"
CONF_INVERTER_LIMIT = "inverter_ac_limit_kw"
CONF_EXPORT_LIMIT = "export_limit_kw"
CONF_SITE_IMPORT_LIMIT = "site_import_limit_kw"
CONF_BATTERY_EXPORT_ENABLED = "battery_export_enabled"
CONF_PROPOSAL_SOLAR_ENABLED = "proposal_solar_enabled"
CONF_PROPOSAL_SOLAR_FACTOR = "proposal_solar_factor"
CONF_GAS_KWH_PER_M3 = "gas_kwh_per_m3"
CONF_BATTERY_POWER_POSITIVE_IS_DISCHARGE = "battery_power_positive_is_discharge"
CONF_SIMULATION_STRATEGY = "simulation_strategy"
CONF_SAVING_SESSION_ENABLED = "saving_session_enabled"

CONF_SYSTEM_COST = "system_cost_gbp"
CONF_ADDITIONAL_COSTS = "additional_costs_gbp"
CONF_GRANTS_REBATES = "grants_rebates_gbp"
CONF_COMMISSIONING_DATE = "commissioning_date"
CONF_ANNUAL_MAINTENANCE = "annual_maintenance_gbp"
CONF_MANUAL_SYSTEM_COSTS = "manual_system_costs_gbp"
CONF_ELECTRICITY_INFLATION = "electricity_inflation_percent"
CONF_BATTERY_DEGRADATION = "battery_degradation_percent"
CONF_DISCOUNT_RATE = "discount_rate_percent"
CONF_ROI_FORECAST_YEARS = "roi_forecast_years"

CONF_OPERATING_MODE = "operating_mode"
CONF_VIRTUAL_SCENARIO = "virtual_scenario"
CONF_CONTROL_ENABLED = "control_enabled"
CONF_SYSTEM_COMMISSIONED = "system_commissioned"
CONF_EMERGENCY_STOP = "emergency_stop"
CONF_STALE_DATA_SECONDS = "stale_data_seconds"
CONF_GRID_STABILITY_SECONDS = "grid_stability_seconds"
CONF_EPS_LIMIT = "eps_limit_kw"
CONF_EPS_WARNING_PERCENT = "eps_warning_percent"
CONF_EPS_CRITICAL_PERCENT = "eps_critical_percent"
CONF_ISLAND_RESERVE_PERCENT = "island_reserve_percent"

CONF_FORECAST_ENABLED = "forecast_enabled"
CONF_FORECAST_OPEN_METEO_ENABLED = "forecast_open_meteo_enabled"
CONF_FORECAST_OPEN_METEO_REFRESH_MINUTES = "forecast_open_meteo_refresh_minutes"
CONF_FORECAST_PERFORMANCE_RATIO = "forecast_performance_ratio"
CONF_FORECAST_RESERVE_SAFETY_MARGIN_PERCENT = "forecast_reserve_safety_margin_percent"
CONF_FORECAST_WATCH_MARGIN_KWH = "forecast_watch_margin_kwh"
CONF_FORECAST_RECOVERY_MARGIN_KWH = "forecast_recovery_margin_kwh"

DEFAULT_OPTIONS = {
    CONF_TARIFF_MODE: "automatic",
    CONF_MANUAL_DAY_RATE: 28.3036,
    CONF_MANUAL_OFFPEAK_RATE: 3.4933,
    CONF_MANUAL_STANDING_CHARGE: 53.70435,
    CONF_MANUAL_OFFPEAK_START: "23:30:00",
    CONF_MANUAL_OFFPEAK_END: "05:30:00",
    CONF_INTELLIGENT_SLOTS_ENABLED: True,
    CONF_SCAN_INTERVAL: DEFAULT_SCAN_INTERVAL_SECONDS,
    CONF_HISTORY_DAYS: DEFAULT_HISTORY_DAYS,
    CONF_BATTERY_CAPACITY: 56.42,
    CONF_BATTERY_RESERVE: 10.0,
    CONF_BATTERY_INITIAL: 10.0,
    CONF_MAX_CHARGE: 7.0,
    CONF_MAX_DISCHARGE: 7.0,
    CONF_CHARGE_EFFICIENCY: 0.95,
    CONF_DISCHARGE_EFFICIENCY: 0.95,
    CONF_EXPORT_RATE: 12.0,
    CONF_EXPORT_TARIFF_STATUS: "active",
    CONF_INVERTER_LIMIT: 7.0,
    CONF_EXPORT_LIMIT: 7.0,
    CONF_SITE_IMPORT_LIMIT: 0.0,
    CONF_BATTERY_EXPORT_ENABLED: True,
    CONF_PROPOSAL_SOLAR_ENABLED: True,
    CONF_PROPOSAL_SOLAR_FACTOR: 1.0,
    CONF_GAS_KWH_PER_M3: 11.1868,
    CONF_BATTERY_POWER_POSITIVE_IS_DISCHARGE: True,
    CONF_SIMULATION_STRATEGY: "paced_export",
    CONF_SAVING_SESSION_ENABLED: True,
    CONF_SYSTEM_COST: 20995.0,
    CONF_ADDITIONAL_COSTS: 0.0,
    CONF_GRANTS_REBATES: 0.0,
    CONF_COMMISSIONING_DATE: "",
    CONF_ANNUAL_MAINTENANCE: 0.0,
    CONF_MANUAL_SYSTEM_COSTS: 0.0,
    CONF_ELECTRICITY_INFLATION: 3.0,
    CONF_BATTERY_DEGRADATION: 2.0,
    CONF_DISCOUNT_RATE: 6.75,
    CONF_ROI_FORECAST_YEARS: 20,
    CONF_OPERATING_MODE: "simulate",
    CONF_VIRTUAL_SCENARIO: "normal",
    CONF_CONTROL_ENABLED: False,
    CONF_SYSTEM_COMMISSIONED: False,
    CONF_EMERGENCY_STOP: False,
    CONF_STALE_DATA_SECONDS: 180,
    CONF_GRID_STABILITY_SECONDS: 300,
    CONF_EPS_LIMIT: 7.0,
    CONF_EPS_WARNING_PERCENT: 70.0,
    CONF_EPS_CRITICAL_PERCENT: 90.0,
    CONF_ISLAND_RESERVE_PERCENT: 20.0,
    CONF_FORECAST_ENABLED: True,
    CONF_FORECAST_OPEN_METEO_ENABLED: True,
    CONF_FORECAST_OPEN_METEO_REFRESH_MINUTES: 30,
    CONF_FORECAST_PERFORMANCE_RATIO: 0.85,
    CONF_FORECAST_RESERVE_SAFETY_MARGIN_PERCENT: 5.0,
    CONF_FORECAST_WATCH_MARGIN_KWH: 3.0,
    CONF_FORECAST_RECOVERY_MARGIN_KWH: 1.0,
}
