name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Why would this help?