name: Validate KEMS

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate JSON files
        run: |
          python -m json.tool custom_components/kems/manifest.json > /dev/null
          python -m json.tool hacs.json > /dev/null